version: '3.8'

services:
  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/php:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php

  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./:/var/www/php
    depends_on:
      - mysql

  mysql:
    # image: mysql:8
    build: ./.docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Webtintuc
    volumes:
      - ./.docker/mysql/my.conf:/etc/mysql/conf.d/my.conf:ro
      - ./.docker/mysql/web.sql:/docker-entrypoint-initdb.d/web.sql:ro
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysqldata: